// src/renderer/features/SELECT_PORTFOLIO/portTableColumns.js

export const ALL_PORT_COLUMN_KEYS = [
  '1_BASE',
  '1_LOCAL',
  '10_BASE',
  '10_LOCAL',
  '11_BASE',
  '11_LOCAL',
  '12_BASE',
  '12_LOCAL',
  '13_BASE',
  '13_LOCAL',
  '14_BASE',
  '14_LOCAL',
  '15_BASE',
  '15_LOCAL',
  '16_BASE',
  '16_LOCAL',
  '17_BASE',
  '17_LOCAL',
  '18_BASE',
  '18_LOCAL',
  '19_BASE',
  '19_LOCAL',
  '2_BASE',
  '2_LOCAL',
  '20_BASE',
  '20_LOCAL',
  '21_BASE',
  '21_LOCAL',
  '22_BASE',
  '22_LOCAL',
  '23_BASE',
  '23_LOCAL',
  '24_BASE',
  '24_LOCAL',
  '25_BASE',
  '25_LOCAL',
  '26_BASE',
  '26_LOCAL',
  '27_BASE',
  '27_LOCAL',
  '28_BASE',
  '28_LOCAL',
  '29_BASE',
  '29_LOCAL',
  '3_BASE',
  '3_LOCAL',
  '30_BASE',
  '30_LOCAL',
  '4_BASE',
  '4_LOCAL',
  '5_BASE',
  '5_LOCAL',
  '6_BASE',
  '6_LOCAL',
  '7_BASE',
  '7_LOCAL',
  '8_BASE',
  '8_LOCAL',
  '9_BASE',
  '9_LOCAL',
  'adjusted_rating',
  'BASE_CCY',
  'C_SPREAD',
  'C_SPREAD_BASE',
  'C_SPREAD_DELTA',
  'CAP',
  'CATEGORY',
  'CCY',
  'clean_price',
  'COUPON',
  'CouponType',
  'CPV01',
  'CPV01_BASE',
  'CPV01_LOCAL',
  'CPV01rel',
  'CS_Szenario',
  'Depotbank',
  'DESCRIPTION',
  'FINLIB',
  'FLOOR',
  'FX_PAIR',
  'FX_RATE',
  'FX_TO_BASE',
  'GEARING',
  'INCLUDE',
  'ISSUER',
  'MATURITY',
  'MATURITY_YEAR',
  'METHODE',
  'MODEL',
  'NAV',
  'NAV_BASE',
  'NAV_LOCAL',
  'NOTIONAL',
  'port_name',
  'PRICE_BUY',
  'PROD_ID',
  'PV_BASE',
  'PV_LOCAL',
  'PV01',
  'PV01_BASE',
  'PV01_LOCAL',
  'PV01rel',
  'RANK',
  'RATING',
  'RATING_PROD',
  'RATINGres',
  'ratings_numeric',
  'SCHEDULE',
  'SPREADS',
  'START_DATE',
  'TENOR',
  'TICKER',
  'TRADE_DATE',
  'TRADE_ID',
  'TtM',
  'ytm',
  'ytm_BUY',
  'ytmPort',
  'ytmPortA',
];

export const SELECTABLE_PORT_COLUMNS = [
  { key: 'CATEGORY', label: 'Kategorie' },
  { key: 'clean_price', label: 'Preis aktuell' },
  { key: 'COUPON', label: 'Zinssatz/Coupon' },
  { key: 'CouponType', label: 'Coupon Type' },
  { key: 'Depotbank', label: 'Depotbank' },
  { key: 'DESCRIPTION', label: 'Beschreibung' },
  { key: 'ISSUER', label: 'Emittent' },
  { key: 'MATURITY', label: 'Fälligkeit' },
  { key: 'MATURITY_YEAR', label: 'Jahr Fälligkeit' },
  { key: 'NAV', label: 'Wert aktuell' },
  { key: 'NOTIONAL', label: 'Nominale' },
  { key: 'PRICE_BUY', label: 'Preis Kauf' },
  { key: 'PROD_ID', label: 'ISIN' },
  { key: 'RANK', label: 'Rank' },
  { key: 'RATING', label: 'Rating Emittent' },
  { key: 'RATING_PROD', label: 'Rating Produkt' },
  { key: 'RATINGres', label: 'Rating' },
  { key: 'START_DATE', label: 'Startdatum Produkt' },
  { key: 'TENOR', label: 'Tenor' },
  { key: 'TICKER', label: 'Ticker' },
  { key: 'TRADE_DATE', label: 'Handelstag' },
  { key: 'TRADE_ID', label: 'Trade ID' },
  { key: 'TtM', label: 'Time to Maturity' },
  { key: 'ytm', label: 'Yield to Maturity' },
  { key: 'ytm_BUY', label: 'YTM Kauf' },
];

export const SELECTABLE_PORT_COLUMN_KEYS = SELECTABLE_PORT_COLUMNS.map(col => col.key);

// export const DEFAULT_VISIBLE_PORT_COLUMN_KEYS = [...SELECTABLE_PORT_COLUMN_KEYS];
export const DEFAULT_VISIBLE_PORT_COLUMN_KEYS = [
  'CATEGORY',  
  'PROD_ID',
  'DESCRIPTION',
  'Depotbank',
  'ISSUER',
  'MATURITY',
  'RATINGres',
  'NOTIONAL',
  'NAV',  
];

export function getPortColumnLabel(columnKey) {
  const column = SELECTABLE_PORT_COLUMNS.find(col => col.key === columnKey);
  return column ? column.label : columnKey;
}

export const ALL_PORT_COLUMNS = ALL_PORT_COLUMN_KEYS.map((key) => ({
  key,
  label: getPortColumnLabel(key),
}));