export const PORTFOLIO_TABLE_NAME = 'Portfolios';

export const PORTFOLIO_INTERNAL_COLUMNS = [
  'TRADE_ID',
  'PROD_ID',
  'DESCRIPTION',
  'CATEGORY',
  'COUPON',
  'Depotbank',
  'CouponType',
  'MATURITY',
  'ISSUER',
  'RANK',
  'RATING',
  'RATINGres',
  'C_SPREAD',
  'C_SPREAD_BASE',
  'C_SPREAD_DELTA',
  'NOTIONAL',
  'PRICE_BUY',
  'clean_price',
  'NAV',

  // wichtig für Aggregate, kommt NICHT mehr aus Portfolios,
  // sondern wird vorher aus PortfolioRiskSensitivities angereichert
  'PV01',
  'CPV01',

  'ytm_BUY',
  'ytm',
  'ytmPort',
  'ytmPortA',
  'MATURITY_YEAR',
  'TtM',
];

export const PORTFOLIO_VISIBLE_COLUMNS = [
  'TRADE_ID',
  'PROD_ID',
  'DESCRIPTION',
  'CATEGORY',
  'COUPON',
  'Depotbank',
  'CouponType',
  'MATURITY',
  'ISSUER',
  'RANK',
  'RATING',
  'RATINGres',
  'clean_price',
  'C_SPREAD',
  'C_SPREAD_BASE',
  'C_SPREAD_DELTA',
  'NOTIONAL',
  'PRICE_BUY',
  'NAV',
  'PV01rel',
  'CPV01rel',
  'PV01',
  'CPV01',
  'ytm_BUY',
  'ytm',
  'MATURITY_YEAR',
];